### ISSUE TITLE
Update Player Identifier to Use DNI as Primary Key

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/sistema-de-gestion-deportiva#11]
## Description
We need to update the identifier for the `Player` class from using the player's name to using their DNI. This change is necessary to comply with the requirement that two players, or a player and a team, can have the same name. The new requirement specifies that the **DNI should be used as the unique key for players**.

## Tasks
To implement this change, we will:

1. **Update the `Participant` Interface**:
   - Add a `getKey()` method to the `Participant` interface.

2. **Modify the `Player` Class**:
   - Implement the `getKey()` method in the `Player` class to return the player's DNI as the key.

3. **Define Key for `Team`**:
   - Implement the `getKey()` method in the `Team` class to return the team name as the key.

4. **Update Methods and Data Structures**:
   - Modify all methods and data structures that currently use the player's name as the identifier to use the DNI instead.

5. **Ensure Key Uniqueness**:
   - Ensure there are no conflicts between player names and team names by relying on the new key system.

## Affected Components
The following components will require updates:

- **`Participant` Interface**:
  - Add the `getKey()` method.

- **`Player` Class**:
  - Update to use DNI as the key in the `getKey()` method.

- **`Team` Class**:
  - Define the team name as the key in the `getKey()` method.

- **Methods and Data Structures**:
  - Refactor all instances where players are searched, stored, or compared by name to use the new key system.

## Benefits
- Ensures unique identification of players using their DNI.
- Prevents conflicts between player names and team names.
- Aligns with system requirements for uniqueness and integrity.

## Acceptance Criteria
- All players are uniquely identified by their DNI.
- No conflicts exist between player names and team names.
- All affected methods and data structures function correctly with the new key system.
- All tests pass with the updated implementation.

**Comment by javierdesant** [comment]
There's no need to introduce a new `getKey()` method in the `Participant` interface or to heavily refactor the system. Simply defining custom `equals()` and `hashCode()` methods for the `Player` and `Team` classes is sufficient.

- **For `Player`**: Use `dni` in the `equals()` method.
- **For `Team`**: Use `name` in the `equals()` method.

*If `HashMap` use is needed, override `HashCode` method also for both classes.*

**Comment by javierdesant** [comment]
I found a `HashMap` implementation for player in `Team` class. **We must override `HashCode` in Player class, at least**.

**Comment by JhonyRetro** [comment]
Check out dec25584e1b52fddbfff594987336cd4367b1a36 and a3afb0d524f9c5cf85172163bc067787d6436e4f

I also fixed c4545d7449c5bfa32416d6dafce286c3576c8000 while testing

**Comment by JhonyRetro** [comment]
Forgot to compare values, since each DNI is a different object. 
Fixed in 5b32a10dc2cf87c3739d86d5fdcef50c44b8df5b

**Comment by javierdesant** [comment]
Ty.
I made some final adjustments on d1422503f88215800c9a942c347d87047ac81333 and 67e55a6c18aae77c83d04439d69c4aa199b8091d commits. This is done now.

**Comment by javierdesant** [comment]
We are still looking for players by their names in the lists and commands.
I'm reopening this issue.

**Comment by javierdesant** [comment]
Finally. 17b52b92178c071860436217a1471ee88f71c2f7
