### ISSUE TITLE
Refactor Controller and Commands to Follow SOLID Principles

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/sistema-de-gestion-deportiva#14]
# Refactor Controller and Commands to Follow SOLID Principles

## **Description**:  
The current implementation of the `Controller` class and associated command classes (e.g., `DeletePlayerCommand`) violates key SOLID principles, leading to challenges in maintainability, testability, and scalability. This issue proposes a refactoring of the architecture to address these problems by splitting the `Controller` into responsibility-specific services and adapting commands to depend on these services.  

---

### **Problem Statement**:  
1. **Single Responsibility Principle (SRP)**:  
   - The `Controller` class is a monolithic structure handling user authentication, participant management, tournament organization, and more. This tightly coupled design makes the code hard to modify and understand.  
   - Command classes (e.g., `DeletePlayerCommand`) rely on the `Controller` for all operations, which combines business logic and interaction logic.  

2. **Open/Closed Principle (OCP)**:  
   - Adding new features to the `Controller` requires modifying existing methods, potentially introducing regressions.  

3. **Dependency Inversion Principle (DIP)**:  
   - Commands depend directly on a concrete implementation (`Controller`), reducing flexibility and testability.  

4. **Testability**:  
   - The current design couples commands tightly with the `Controller`, making isolated unit tests difficult without significant setup.

---

### **Proposed Solution**:  

1. **Decompose the `Controller` Class**:
   - Split the `Controller` into smaller, domain-specific service classes:
     - **`AuthenticationService`**: Handles login, logout, and user session management.
     - **`ParticipantService`**: Manages participants (players and teams) and related operations (e.g., adding/removing from teams).
     - **`TournamentService`**: Handles tournament creation, deletion, matchmaking, and enrollment.  

2. **Refactor Command Classes**:
   - Each command should depend on the specific service(s) it requires rather than the `Controller`.  
   - For example, the `DeletePlayerCommand` should depend on the `ParticipantService`, making it more focused and testable.  

3. **Introduce Interfaces for Services**:
   - Define interfaces for the service classes (e.g., `IParticipantService`, `IAuthenticationService`) to enable easier mocking and alternative implementations in the future.  

4. **Centralize Dependency Injection**:
   - Use dependency injection (e.g., constructor-based) to provide services to commands, decoupling them from concrete implementations.  

---

### **Acceptance Criteria**:  
- [x] Create `AuthenticationService`, `ParticipantService`, and `TournamentService` classes.  
- [x] Move corresponding methods from the `Controller` to the respective service classes.  
- [x] Refactor all command classes to use the new services instead of the `Controller`.  
- [x] Define interfaces for all service classes.  
- [x] Ensure all affected classes have updated unit tests to validate the new architecture.  
- [x] Remove unused methods and logic from the `Controller`.  
- [x] Update documentation to reflect the new architecture.  

---

#### **Before (Current Code)**:  

`DeletePlayerCommand` depends on `Controller` and handles some validation logic:  

```java
public class DeletePlayerCommand extends Command {
    private final Controller controller;

    public DeletePlayerCommand(Controller controller) {
        super("player-remove", 1, "Deletes a player if they aren't in a tournament or team.");
        this.controller = controller;
    }

    @Override
    protected ErrorType execute(CommandArguments args) {
        String playerDni = args.pollToken();
        if (!DNI.isValidDNI(playerDni)) {
            return ErrorType.INVALID_DNI_ERROR;
        }
        return this.controller.deletePlayer(DNI.valueOf(playerDni));
    }
}
```

#### **After (Refactored Code)**:  

`DeletePlayerCommand` depends on `ParticipantService`, delegating business logic and validation:

```java
public class DeletePlayerCommand extends Command {
    private final ParticipantService participantService;

    public DeletePlayerCommand(ParticipantService participantService) {
        super("player-remove", 1, "Deletes a player if they aren't in a tournament or team.");
        this.participantService = participantService;
    }

    @Override
    protected ErrorType execute(CommandArguments args) {
        String playerDni = args.pollToken();
        if (!DNI.isValidDNI(playerDni)) {
            return ErrorType.INVALID_DNI_ERROR;
        }
        return this.participantService.deletePlayer(DNI.valueOf(playerDni));
    }
}
```

**Comment by JhonyRetro** [comment]
It should be noted that we need to fix tournament commands' related problems. Will look into it tomorrow. ✌

**Comment by javierdesant** [comment]
All yours brother. 🫡
