### ISSUE TITLE
Enviar la prática

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/sistema-de-gestion-deportiva#20]
Entregar este domingo 8.

Podéis hacer la release, mergear master y develop y luego enviar el código o enviarlo directamente desde develop.
Lo importante es que esté en plazo, aunque no quede perfecta.

---

```
También quedaría enviarlo.
Por favor enviarlo en el plazo, que yo no estoy.
```
_Originally posted by @javierdesant in https://github.com/javierdesant/sistema-de-gestion-deportiva/issues/19#issuecomment-2521963106_

**Comment by JhonyRetro** [comment]
Me encargo mañana, actualizaré el pom, los puml y el resto de docs
