### ISSUE TITLE
Replace players in Match class with an array

### ISSUE THREAD

**Issue by JhonyRetro** [javierdesant/sistema-de-gestion-deportiva#4]
# Descripción del problema
Sustituir los atributos homePlayer y visitingPlayer por un array de dos elementos (jugadores).

# Ventajas 
Utilización de métodos relacionados al array, reducción de código, y optimización de métodos de la clase Match.

**Comment by javierdesant** [comment]
Este bug hay que trabajarlo en la rama [feature/playersArray](https://github.com/javierdesant/sistema-de-gestion-deportiva/tree/feature/playersArray).

- `git checkout feature/playersArray`
